### ISSUE TITLE
Dashboard Design

### ISSUE THREAD

**Issue by de-marauder** [zuri-training/Proj-T_C_Gen-Team-74#15]
## Create the Users Dashboard Design

**Comment by Omolahrah** [comment]
This is completed.

**Comment by labodinho** [comment]
Figma Link to task [CLICK THIS TO FIGMA](https://www.figma.com/file/sn6pQ7kYLokvXTVimlwFVv/Team-74-Project-Phase-design?node-id=2%3A3)
