### ISSUE TITLE
Design the T&C generator output page

### ISSUE THREAD

**Issue by de-marauder** [zuri-training/Proj-T_C_Gen-Team-74#29]
## Produce the figma designs for the page that displays the generated output

**Comment by labodinho** [comment]
Figma Link to task [CLICK THIS TO FIGMA](https://www.figma.com/file/sn6pQ7kYLokvXTVimlwFVv/Team-74-Project-Phase-design?node-id=2%3A3)

**Comment by labodinho** [comment]
Figma Link to task [CLICK THIS TO FIGMA](https://www.figma.com/file/sn6pQ7kYLokvXTVimlwFVv/Team-74-Project-Phase-design?node-id=2%3A3)

**Comment by labodinho** [comment]
Figma Link to task [CLICK THIS TO FIGMA](https://www.figma.com/file/sn6pQ7kYLokvXTVimlwFVv/Team-74-Project-Phase-design?node-id=2%3A3)

**Comment by labodinho** [comment]
Figma Link to task [CLICK THIS TO FIGMA](https://www.figma.com/file/sn6pQ7kYLokvXTVimlwFVv/Team-74-Project-Phase-design?node-id=2%3A3)
