### ISSUE TITLE
UX research documentation

### ISSUE THREAD

**Issue by de-marauder** [zuri-training/Proj-T_C_Gen-Team-74#35]
## Assist in the UX research documentation

**Comment by Damilola-designer** [comment]
Okay, on it.

**Comment by labodinho** [comment]
Figma Link to task [CLICK THIS TO FIGMA](https://www.figma.com/file/sn6pQ7kYLokvXTVimlwFVv/Team-74-Project-Phase-design?node-id=2%3A3)
