### ISSUE TITLE
Documentation page and Templates 

### ISSUE THREAD

**Issue by labodinho** [zuri-training/Proj-T_C_Gen-Team-74#5]

**Comment by lteTraveller** [comment]
[blog_PP_temp.md](https://github.com/zuri-training/Proj-T_C_Gen-Team-74/files/9226108/blog_PP_temp.md)
[ecommerce_PP_temp.md](https://github.com/zuri-training/Proj-T_C_Gen-Team-74/files/9226109/ecommerce_PP_temp.md)
[ecommerce_T&C_temp.md](https://github.com/zuri-training/Proj-T_C_Gen-Team-74/files/9226110/ecommerce_T.C_temp.md)
[mobile_app_PP_temp.md](https://github.com/zuri-training/Proj-T_C_Gen-Team-74/files/9226111/mobile_app_PP_temp.md)
[mobile_app_T&C_temp.md](https://github.com/zuri-training/Proj-T_C_Gen-Team-74/files/9226112/mobile_app_T.C_temp.md)
[privacy_policy_template.md](https://github.com/zuri-training/Proj-T_C_Gen-Team-74/files/9226113/privacy_policy_template.md)
[saas_T&C_temp.md](https://github.com/zuri-training/Proj-T_C_Gen-Team-74/files/9226114/saas_T.C_temp.md)
[small_biz_PP_temp.md](https://github.com/zuri-training/Proj-T_C_Gen-Team-74/files/9226115/small_biz_PP_temp.md)
[small_biz_T&C_temp.md](https://github.com/zuri-training/Proj-T_C_Gen-Team-74/files/9226116/small_biz_T.C_temp.md)
[T&C_temp.md](https://github.com/zuri-training/Proj-T_C_Gen-Team-74/files/9226117/T.C_temp.md)
