### ISSUE TITLE
Form Page

### ISSUE THREAD

**Issue by labodinho** [zuri-training/Proj-T_C_Gen-Team-74#52]
Assist in designing the form page

**Comment by AbdulMunim21** [comment]
I can help. Do you have any UI designs related to form?

**Comment by de-marauder** [comment]
> 

Sorry this project is not open for this type of contribution. We already have a team

**Comment by labodinho** [comment]
Figma Link to task [CLICK THIS TO FIGMA](https://www.figma.com/file/sn6pQ7kYLokvXTVimlwFVv/Team-74-Project-Phase-design?node-id=2%3A3)
