### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by labodinho** [zuri-training/Proj-T_C_Gen-Team-74#53]
More hands needed on the dashboard page to improve the design.

**Comment by Omolahrah** [comment]
Design has been completed by @Omolahrah and @Zooneey (2 days back) and confirmed good to go by team.

**Comment by labodinho** [comment]
Figma Link to task [CLICK THIS TO FIGMA](https://www.figma.com/file/sn6pQ7kYLokvXTVimlwFVv/Team-74-Project-Phase-design?node-id=2%3A3)
